package main

import (
	"bytes"
	"cmp"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"unicode"

	"slices"

	"github.com/iancoleman/strcase"
)

var (
	inputPath   string
	outputFile  string
	packageName string
)

func init() {
	flag.StringVar(&inputPath, "i", "", "")
	flag.StringVar(&outputFile, "o", "", "")
	flag.StringVar(&packageName, "pkg", "", "")
}

type Pair struct {
	Enum  string
	Value int64
}

type TypedefEnum struct {
	Name   string
	GoType string
	Enums  []Pair
}

type Enums []TypedefEnum

func (e Enums) Add(goType, t string, enum string, value int64) Enums {
	found := false
	for i, v := range e {
		if v.Name == t {
			found = true
			v.Enums = append(v.Enums, Pair{
				Enum:  enum,
				Value: value,
			})
			e[i] = v
		}
	}

	if !found {
		e = append(e, TypedefEnum{
			Name:   t,
			GoType: goType,
			Enums: []Pair{{
				Enum:  enum,
				Value: value,
			}},
		})
	}
	return e
}

func main() {
	flag.Parse()

	var in string

	files := mustv(filepath.Glob(inputPath + "/*.h"))
	for _, file := range files {
		fmt.Println("reading", file)
		in += string(mustv(os.ReadFile(file)))
	}

	var enums = Enums{}

	re := regexp.MustCompile("(?m)^(static const .*)?\\s*WGPU([A-Za-z0-9]+)_([A-Za-z0-9]+) = 0x([0-9A-F]+)")

	for _, match := range re.FindAllStringSubmatch(in, -1) {
		goType := "uint32"
		if match[1] != "" {
			goType = "uint64"
		}

		typ := match[2]
		name := match[3]
		fullname := typ + name
		value, _ := strconv.ParseInt(match[4], 16, 64)

		if typ == "NativeFeature" {
			typ = "FeatureName"
		}

		if name == "Force32" || typ == "SType" {
			continue
		}

		enums = enums.Add(goType, typ, fullname, value)
	}

	slices.SortStableFunc(enums, func(a, b TypedefEnum) int {
		return cmp.Compare(a.Name, b.Name)
	})

	w := &bytes.Buffer{}

	fmt.Fprintf(w, "// Code generated by github.com/dhannyell/webgpu/cmd/enums; DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n\n", packageName)
	
	fmt.Fprintln(w, `import "fmt"`)

	for _, e := range enums {
		slices.SortStableFunc(e.Enums, func(a, b Pair) int {
			return cmp.Compare(a.Value, b.Value)
		})

		fmt.Fprintf(w, "type %s %s\n\n", e.Name, e.GoType)
		for _, v := range e.Enums {
			enum := v.Enum
			value := v.Value
			fmt.Fprintf(w, "const %s %s = 0x%.8X\n", enum, e.Name, value)
		}

		fmt.Fprint(w, "\n")

		if e.Name == "VertexFormat" {
			generateVertexFormatSize(w, e)
		}

		fmt.Fprintf(w, "func (v %s) String() string {\n", e.Name)
		fmt.Fprintf(w, "switch v {\n")
		for _, v := range e.Enums {
			fmt.Fprintf(w, "case %s:\n", v.Enum)
			// Kebab case is consistent with the enum values in JS.
			str := strcase.ToKebab(strings.TrimPrefix(v.Enum, e.Name))
			// Remove any hyphens connected to a digit, as JS does not include them.
			b := strings.Builder{}
			rs := []rune(str)
			for i, r := range rs {
				if r == '-' {
					if i > 0 && unicode.IsDigit(rs[i-1]) {
						continue
					}
					if i < len(rs)-1 && unicode.IsDigit(rs[i+1]) {
						continue
					}
				}
				b.WriteRune(r)
			}
			fmt.Fprintf(w, "return \"%s\"\n", b.String())
		}
		if e.Name == "ErrorType" {
			fmt.Fprintf(w, "default:\n")
			fmt.Fprintf(w, "return \"unknown\"\n")
		} else {
			fmt.Fprintf(w, "default:\n")
			fmt.Fprintf(w, "return \"\"\n")
		}
		fmt.Fprintf(w, "}\n")
		fmt.Fprintf(w, "}\n")
	}

	out := mustv(os.Create(outputFile))
	mustv(out.Write(fmtFile(w.Bytes())))
	must(out.Close())
}

func generateVertexFormatSize(w io.Writer, enum TypedefEnum) {
	re := regexp.MustCompile("([0-9]+)(?:x([1234]+))?")

	fmt.Fprintln(w, "func (v VertexFormat) ByteSize() uint32 {")
	fmt.Fprintln(w, "switch v {")

	for _, enumItem := range enum.Enums {
		match := re.FindStringSubmatch(enumItem.Enum)
		if match == nil {
			panic("no match in " + enumItem.Enum)
		}

		bitSize, _ := strconv.Atoi(match[1])

		var componentCount = 1
		if match[2] != "" {
			componentCount, _ = strconv.Atoi(match[2])
		}

		fmt.Fprintf(w, "case %s: return %d\n", enumItem.Enum, bitSize/8*componentCount)
	}

	//goland:noinspection GoPrintFunctions
	fmt.Fprintln(w, "default: panic(fmt.Errorf(`unknown size: %s`, v))")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "}")
}

func fmtFile(b []byte) []byte {
	b, err := format.Source(b)
	if err != nil {
		log.Fatalf("cannot run 'go fmt' on file: %v", err)
	}

	return b
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func mustv[T any](v T, err error) T {
	if err != nil {
		panic(err)
	}
	return v
}
