package main

import (
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

var (
	path string
)

func init() {
	flag.StringVar(&path, "i", "", "Path that contains the wgpu source files")
}

func listUsed() []string {
	re := regexp.MustCompile(`\bC.((?:go_)?wgpu[A-Z][A-Za-z]+)`)

	seen := map[string]bool{}
	var names []string

	files := mustv(filepath.Glob(path + "/*.go"))
	for _, file := range files {
		source := string(mustv(os.ReadFile(file)))
		for _, match := range re.FindAllStringSubmatch(source, -1) {
			fn := match[1]

			if !seen[fn] {
				seen[fn] = true
				names = append(names, fn)
			}
		}
	}

	slices.Sort(names)

	return names
}

func main() {
	flag.Parse()

	{
		code := generateHints()
		writeTo(path+"/cgohints.go", fmtGo(code))
	}

	{
		code := generateWrappers()
		writeTo(path+"/gen_wgpu_wrappers.h", fmtC(code))
	}
}

// drainsCallbacks reports whether wgpu may run previously scheduled callbacks
// while inside fn. Those must not be marked #cgo nocallback: the moment one
// comes due the Go runtime aborts the process with "function marked with #cgo
// nocallback called back into Go".
//
// Anything that maintains the device can drain its callback queue. That is
// wgpuDevicePoll and the submit entry points by design, and the surface
// operations as a consequence — reconfiguring a swapchain waits for pending
// work first, and waiting is when queued callbacks run. A caller only reaches
// this if it uses asynchronous buffer mapping, which is why the whole family
// went unnoticed until timestamp queries were read back every frame.
//
// Tearing an object down settles the callbacks it still owes. Dropping the
// last reference to a buffer whose map has not completed invokes the map
// callback with an aborted status from inside wgpuBufferRelease, and unmapping
// a map that is still in flight does the same. Releasing is how a program
// exits, so this is the variant that shows up as a crash on the close button.
//
// The cost of being wrong in this direction is a lost optimisation on a
// handful of calls, none of them per-draw. The cost of being wrong in the
// other direction is a crash, so the list errs wide.
func drainsCallbacks(fn string) bool {
	switch {
	case fn == "wgpuDevicePoll":
		return true
	case strings.HasPrefix(fn, "wgpuQueueSubmit"):
		return true
	case strings.HasPrefix(fn, "wgpuSurface"):
		return true
	case strings.HasSuffix(fn, "Release"), strings.HasSuffix(fn, "Destroy"):
		return true
	case fn == "wgpuBufferUnmap":
		return true
	}
	return false
}

func generateHints() string {
	withCallback := map[string]bool{}
	for _, fn := range FindFunctions() {
		if strings.Contains(fn.Params, "Callback") {
			withCallback[fn.Name] = true
		}

		if fn.RetType == "WGPUFuture" {
			withCallback[fn.Name] = true
		}
	}

	var code []string
	code = append(code, "// Code generated by cmd/cgohints: DO NOT EDIT.\n")
	code = append(code, "//go:build !js")
	code = append(code, "package wgpu")

	code = append(code, "/*")

	for _, fn := range listUsed() {
		fnWGPU := strings.TrimPrefix(fn, "go_")
		if withCallback[fnWGPU] {
			fmt.Println("Skipping function with callback:", fn)
			continue
		}

		if drainsCallbacks(fnWGPU) {
			continue
		}

		code = append(code, "#cgo noescape "+fn)
		code = append(code, "#cgo nocallback "+fn)
	}

	code = append(code, "*/")
	code = append(code, `import "C"`)

	return strings.Join(code, "\n")
}

func writeTo(path string, content string) {
	out, err := os.Create(path)
	if err != nil {
		panic(err)
	}

	defer doClose(out)

	mustv(out.WriteString(content))
}

func doClose(out io.Closer) {
	_ = out.Close()
}

type Function struct {
	RetType string
	Name    string
	Params  string
}

func FindFunctions() (funcs []Function) {
	webgpuH := string(mustv(os.ReadFile(path + "/lib/linux/arm64/webgpu.h")))

	re := regexp.MustCompile(`(?m)^WGPU_EXPORT(?: WGPU_NULLABLE)? (\S+) (wgpu[^(]+)\((.*)\)`)

	for _, match := range re.FindAllStringSubmatch(webgpuH, -1) {
		funcs = append(funcs, Function{
			RetType: match[1],
			Name:    match[2],
			Params:  match[3],
		})
	}

	return
}

func generateWrappers() string {
	var lines []string
	lines = append(lines, "// Code generated by cmd/cgohints: DO NOT EDIT.\n")

	lines = append(lines, `
		#pragma once
	
		#include <stdlib.h>
		#include <string.h>
		#include <wgpu.h>
	
		static inline size_t error_buf_size() {
			return 16 * 1024;
		}
		
		static inline void webgpu_error_callback(WGPUPopErrorScopeStatus status, WGPUErrorType type, WGPUStringView message, WGPU_NULLABLE void* userdata1, WGPU_NULLABLE void* userdata2) {
			char* err = (char *)userdata1;
			if (type == WGPUErrorType_NoError) {
				return;
			}
	
			// handle the case that we get a null data pointer
			if (message.data == NULL) {
				message.data = "unknown error";
				message.length = WGPU_STRLEN;
			}

			// update length if not specified
			if (message.length == WGPU_STRLEN) {
				message.length = strlen(message.data);
			}
			
			// cap message length to available buffer size
			size_t buf_size = error_buf_size();
			if (message.length > buf_size - 1) {
				message.length = buf_size - 1;
			}
	
			// now we can just copy the data over
			memcpy(err, message.data, message.length);
			
			// and set the zero byte at the end
			err[message.length] = 0;
		}
	`)

	for _, fn := range FindFunctions() {
		var paramValues []string

		reValue := regexp.MustCompile(`([a-zA-Z0-9]+)(,|$)`)
		for _, match := range reValue.FindAllStringSubmatch(fn.Params, -1) {
			paramValues = append(paramValues, match[1])
		}

		var returnVar, returnStmt string
		if fn.RetType != "void" {
			returnVar = fn.RetType + " ret = "
			returnStmt = "return ret;"
		}

		lines = append(lines, fmt.Sprintf(`
			static inline %[6]s go_%[1]s(WGPUDevice _dev, char *err, %[2]s) {
				wgpuDevicePushErrorScope(_dev, WGPUErrorFilter_Validation);
				%[4]s %[1]s(%[3]s);
			
				WGPUPopErrorScopeCallbackInfo const err_cb = {
					.callback = webgpu_error_callback,
					.userdata1 = (void*) err,
				};
			
				wgpuDevicePopErrorScope(_dev, err_cb);
				%[5]s
			}
			`,
			fn.Name,
			fn.Params,
			strings.Join(paramValues, ", "),
			returnVar,
			returnStmt,
			fn.RetType,
		))

		lines = append(lines, "")
	}

	return strings.Join(lines, "\n")
}

func fmtGo(input string) string {
	b, err := format.Source([]byte(input))
	if err != nil {
		fmt.Println()
		fmt.Println(input)
		fmt.Println()
		log.Fatalf("cannot run 'go fmt' on file: %v", err)
	}

	return string(b)
}

func fmtC(input string) string {
	var w strings.Builder

	cmd := exec.Command("clang-format")
	cmd.Stdin = strings.NewReader(input)
	cmd.Stdout = &w
	must(cmd.Run())

	return w.String()
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func mustv[T any](v T, err error) T {
	if err != nil {
		panic(err)
	}
	return v
}
